-- ================================================================
--
-- @version $Id: structure.sql 2015-11-10 10:12:05 gewa $
-- @package PHP Help Manager v2.0
-- @copyright 2015.
--
-- ================================================================
-- Database structuredata
-- ================================================================

--
-- Dumping data for table `config`
--

INSERT INTO `{$db_prefix}config` (`config_name`, `config_value`) VALUES
('sitethemes', 'helpdesk'),
('session_id', 'user_helpdesk_id'),
('session_name', 'user_helpdesk_name'),
('charset', 'UTF-8'),
('dateformat', 'F j, Y'),
('sitekey', 'Site wide Meta Keywords'),
('sitedesc', 'Site wide Meta Description'),
('session_length', '3600'),
('acp_session_id', 'acp_megatplhelpdesk_id'),
('acp_session_name', 'acp_megatplhelpdesk_name'),
('lastactivity', '3600'),
('typeuploads', 'gif|png|jpg|jpeg|bmp'),
('gzip_compress', '1'),
('per_page', '5'),
('userper_page', '12'),
('per_popular', '5'),
('defaultcatnews', '0'),
('defaultcatarticle', '0'),
('permalink', 'numeric'),
('folderadmin', 'admin'),
('bg_color', '#ffffff'),
('bg_image', ''),
('bg_logo', ''),
('bg_favicon', ''),
('pageabout', ''),
('pageprivacy', ''),
('pagecontact', ''),
('themecolor', ''),
('facebook', '#'),
('twitter', '#'),
('googleplus', '#'),
('youtube', '#'),
('instagram', '#'),
('facebook_status', 'on'),
('twitter_status', 'on'),
('google_status', 'on'),
('youtube_status', 'on'),
('instagram_status', 'on'),
('gravatar', '0'),
('voting', '0'),
('timezone_string', 'Africa/Cairo'),
('timeformat', 'g:i a'),
('version', '2.0'),
('helpdesk_theme_options', 'a:28:{s:8:"iconbox1";s:12:"fa-life-ring";s:9:"titlebox1";s:4:"FAQS";s:8:"linkbox1";s:18:"index.php?mode=faq";s:13:"titlelinkbox1";s:10:"Visit FAQS";s:11:"bgcolorbox1";s:7:"#5CACE2";s:13:"textcolorbox1";s:7:"#ffffff";s:8:"textbox1";s:82:"Did you visit our FAQS section?<br />\r\nYou will probably find the answer right way";s:8:"iconbox2";s:14:"fa-file-text-o";s:9:"titlebox2";s:14:"Knowledge Base";s:8:"linkbox2";s:28:"index.php?mode=knowledgebase";s:13:"titlelinkbox2";s:22:"Browser Knowledge Base";s:11:"bgcolorbox2";s:7:"#E74C3C";s:13:"textcolorbox2";s:7:"#ffffff";s:8:"textbox2";s:89:"We have knowledge articles.<br />\r\nPlease type keywords on the search above or broser it.";s:8:"iconbox3";s:11:"fa-bullhorn";s:9:"titlebox3";s:4:"News";s:8:"linkbox3";s:19:"index.php?mode=news";s:13:"titlelinkbox3";s:12:"Browser News";s:11:"bgcolorbox3";s:7:"#F1C40F";s:13:"textcolorbox3";s:7:"#ffffff";s:8:"textbox3";s:62:"Did you visit our News section?<br />\r\nYou may find help News.";s:23:"cover_background_header";s:73:"";s:12:"title_header";s:22:"PHP Help manager v2.0 ";s:18:"title_header_color";s:7:"#ffffff";s:14:"tagline_header";s:12:"Tagline text";s:20:"tagline_header_color";s:7:"#ffffff";s:18:"Search_show_header";s:2:"on";s:25:"Search_placeholder_header";s:25:"Search the Knowledge base";}'),
('mailer_header', '<blockquote class="ecxgmail_quote" style="max-width: 500px;margin: 10px auto;">\r\n<div dir="rtl">\r\n<table cellspacing="0" cellpadding="0" width="100%" style="color:#666666;background-color:#fafafa;border:1px solid #e7e7e7;border-collapse:collapse">\r\n<tbody><tr>\r\n<td>\r\n<div style="padding:10px"><div class="ecxim">\r\n<table width="100%" dir="ltr" align="center" style="border-collapse:collapse" border="0" cellpadding="0">\r\n<tbody><tr>\r\n<td width="70%">\r\n<span style="font-size:22pt;font-family:Tahoma,sans-serif;color:#666666">  </span>\r\n{$sitename}\r\n</td>\r\n<td width="30%" style="font-size:8pt;color:#666666;text-align:right;">\r\n {$time}\r\n</td>\r\n</tr>\r\n</tbody></table>\r\n<hr color="#E7E7E7" size="1">\r\n</div>\r\n<div style="text-align:left;padding:10px 0 0px 0;color:#444444;font-family:Tahoma,Verdana,sans-serif;font-size:8pt">\r\n'),
('mailer_footer', '<br /><br />\r\n<div class="ecxim">\r\n<hr color="#E7E7E7" size="1">\r\n<div style="font-family:Tahoma,Verdana,sans-serif;font-size:8pt;color:#666666;padding:10px 0px 0px 0;text-align:center;">\r\nCopyright &copy; {$sitename}\r\n</div>\r\n</div>\r\n</div>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</div>\r\n<p style="text-align: center;">Please do not reply to this message.</p>\r\n</blockquote>'),
('mailer_register_activation', '<p style="text-align:left;" dir="ltr">\nHello, {$firstname} {$lastname} ({$username})\n<br><br>\nThank you for signing up for {$sitename}\n<br><br>\nActivating your account. <br>\nClick on the link below or copy and paste it into your browser''s address bar.\n<br><br>\n<a href="{$siteurl}users.php?mode=activate&key={$keyforget}&login={$username}">Activating your account</a>\n</p>'),
('mailer_register', '<p style="text-align:left;" dir="ltr">Hello, {$firstname} {$lastname} ({$username})\r\n<br><br>\r\nWelcome to the <a href="{$siteurl}">{$sitename}</a>\r\n</p>'),
('mailer_forget_password', '<p style="text-align:left" dir="ltr">Hello, {$firstname} {$lastname} ({$username})\n<br>\n<br>\nBeen sent a request to change your password, you can do so by clicking on the following link:\n<br><br>\n<a href="{$siteurl}users.php?mode=forget&key={$keyforget}&login={$username}">\nchange your password</a>\n<br><br><br>\nIf you do not send this request, please ignore this message.\n</p>'),
('mailer_forget_sucess', '<p style="text-align:left" dir="ltr">Hello, {$firstname} {$lastname} ({$username})\r\n<br>\r\n<br>\r\nchange your password\r\n<br><br>\r\n</p>'),
('mailer_update_password', '<p style="text-align:left" dir="ltr">Hello, {$firstname} {$lastname} ({$username})\r\n<br>\r\n<br>\r\nchange your password\r\n<br><br>\r\n</p>'),
('mailer_contact', '<p style="text-align:left" dir="ltr">\r\nusername: {$username}\r\n<br>\r\nemail: {$email}\r\n<br>\r\nsubject: {$subject}\r\n<br>\r\n<br>\r\nmessage:\r\n<br>\r\n{$message}\r\n</p>'),
('registration_status', '1'),
('registration_activation', '1'),
('pageknowledgebase', 'everyone'),
('pagenews', 'everyone'),
('pagefaq', 'everyone'),
('showpageusers', 'everyone'),
('showprofileusers', 'everyone');

-- --------------------------------------------------------

--
-- Dumping data for table `languages`
--

INSERT INTO `{$db_prefix}languages` (`id`, `code`, `name`, `regex`, `active`, `defaultd`) VALUES
('', 'en', 'English', '/^en/i', 1, 1);

-- --------------------------------------------------------

--
-- Dumping data for table `phrases`
--

INSERT INTO `{$db_prefix}phrases` (`id`, `lang_iso`, `varname`, `text`) VALUES
('', 'en', 'about_us', 'About us'),
('', 'en', 'accept', 'Accept'),
('', 'en', 'action', 'Action'),
('', 'en', 'activate', 'activate'),
('', 'en', 'add', 'Add'),
('', 'en', 'add_group', 'Add Group'),
('', 'en', 'add_language', 'Add Language'),
('', 'en', 'add_new', 'Add New'),
('', 'en', 'add_new_article', 'Add New Article'),
('', 'en', 'add_new_categorie', 'Add New Categorie'),
('', 'en', 'add_new_group', 'Add New Group'),
('', 'en', 'add_new_language', 'Add New Language'),
('', 'en', 'add_new_page', 'Add New Page'),
('', 'en', 'add_new_phrase', 'Add New Phrase'),
('', 'en', 'add_new_post', 'Add New Post'),
('', 'en', 'add_phrase', 'Add Phrase'),
('', 'en', 'add_picture', 'Add Picture'),
('', 'en', 'add_user_successfully', 'Add User Successfully'),
('', 'en', 'administrator', 'Administrator'),
('', 'en', 'align1', 'left'),
('', 'en', 'align2', 'center'),
('', 'en', 'align3', 'right'),
('', 'en', 'all_faq', 'ALL FAQ'),
('', 'en', 'all_knowledgebase', 'ALL Knowledgebase'),
('', 'en', 'all_news', 'ALL News'),
('', 'en', 'appearance', 'Appearance'),
('', 'en', 'apply', 'Apply'),
('', 'en', 'as_default_language', 'as Default Language'),
('', 'en', 'author', 'Author'),
('', 'en', 'avatar_image_size_must', 'The image size must be at least 256x256 pixels.'),
('', 'en', 'back', 'Back'),
('', 'en', 'back_to', 'Back To'),
('', 'en', 'been_sent_change_the_password', 'Been Sent Change The Password'),
('', 'en', 'bulk_actions', 'Bulk Actions'),
('', 'en', 'by', 'By'),
('', 'en', 'cancel', 'Cancel'),
('', 'en', 'categorie', 'Categorie'),
('', 'en', 'categories', 'Categories'),
('', 'en', 'cencel', 'Cencel'),
('', 'en', 'change_avatar', 'Change Avatar'),
('', 'en', 'change_cover', 'Change cover'),
('', 'en', 'change_email_address', 'Change email address'),
('', 'en', 'change_password', 'Change password'),
('', 'en', 'click_here_to_login', 'Click here to login'),
('', 'en', 'confirm_action', 'Are you sure of the procedure?'),
('', 'en', 'confirm_password', 'Confirm Password'),
('', 'en', 'contact', 'Contact'),
('', 'en', 'content_is_available_to_members_only', 'Content is available to members only'),
('', 'en', 'copyright', 'copyright © 2015 All Rights Reserved.'),
('', 'en', 'count', 'Count'),
('', 'en', 'cover_background', 'Cover Background'),
('', 'en', 'cover_image_size_must', 'The image size must be at least 1190x260 pixels.'),
('', 'en', 'cover_text_color', 'Cover Text Color'),
('', 'en', 'crop_avatar', 'Crop Avatar'),
('', 'en', 'crop_cover', 'Crop Cover'),
('', 'en', 'dashboard', 'Dashboard'),
('', 'en', 'date', 'Date'),
('', 'en', 'date_format', 'Date Format'),
('', 'en', 'deactivate', 'Deactivate'),
('', 'en', 'delete', 'Delete'),
('', 'en', 'delete_categorie_successfully', 'Delete Categorie Successfully'),
('', 'en', 'delete_language_successfully', 'Delete Language Successfully.'),
('', 'en', 'delete_post_successfully', 'Delete Post successfully.'),
('', 'en', 'delete_users_successfully', 'delete users successfully'),
('', 'en', 'delete_user_successfully', 'delete user successfully'),
('', 'en', 'description', 'Description'),
('', 'en', 'didnot_match', 'didnot match to our content in asked queries!'),
('', 'en', 'dir', 'ltr'),
('', 'en', 'disable', 'Disable'),
('', 'en', 'disable_categorie_successfully', 'Disable Categorie Successfully'),
('', 'en', 'disable_language_successfully', 'Disable Language Successfully.'),
('', 'en', 'disable_post_successfully', 'Disable Post Successfully.'),
('', 'en', 'down', 'Down'),
('', 'en', 'doyou_logout', 'Do you want to log out?'),
('', 'en', 'edit', 'Edit'),
('', 'en', 'editing', 'Editing'),
('', 'en', 'edit_article', 'Edit Article'),
('', 'en', 'edit_categorie', 'Edit Categorie'),
('', 'en', 'edit_groups', 'Edit Groups'),
('', 'en', 'edit_page', 'Edit Page'),
('', 'en', 'edit_phrases', 'Edit Phrases'),
('', 'en', 'edit_post', 'Edit Post'),
('', 'en', 'edit_profile', 'Edit Profile'),
('', 'en', 'edit_user_successfully', 'Edit User Successfully'),
('', 'en', 'email', 'E-mail'),
('', 'en', 'email_address', 'Email Address'),
('', 'en', 'email_address_is_required', 'Email Address is required.'),
('', 'en', 'email_another_user', 'This email user by another user.'),
('', 'en', 'email_available_registration', 'This email is available for registration.'),
('', 'en', 'email_is_hidden', 'Email is hidden.'),
('', 'en', 'email_or_password_is_incorrect', 'E-mail or password is incorrect'),
('', 'en', 'email_templates', 'Email Templates'),
('', 'en', 'enable', 'Enable'),
('', 'en', 'enable_categorie_successfully', 'Enable Categorie Successfully'),
('', 'en', 'enable_language_successfully', 'Enable Language Successfully.'),
('', 'en', 'enable_post_successfully', 'Enable Post Successfully.'),
('', 'en', 'english_only_characters', 'English only characters'),
('', 'en', 'enter_email_address', 'Enter Email address'),
('', 'en', 'enter_message', 'Enter Message'),
('', 'en', 'enter_subject', 'Enter Subject'),
('', 'en', 'enter_the_new_email_address', 'Enter the new Email address'),
('', 'en', 'enter_the_new_password', 'Enter the new password'),
('', 'en', 'enter_title_here', 'Enter title here'),
('', 'en', 'enter_username', 'Enter Username'),
('', 'en', 'error_permission', 'error permission'),
('', 'en', 'everyone', 'Everyone'),
('', 'en', 'export', 'Export'),
('', 'en', 'e_mail', 'E-Mail'),
('', 'en', 'facebook', 'Facebook'),
('', 'en', 'facebook_url', 'Facebook URL'),
('', 'en', 'faq', 'FAQ'),
('', 'en', 'faq_items', 'FAQ Items'),
('', 'en', 'favicon', 'Favicon'),
('', 'en', 'featured_image', 'Featured Image'),
('', 'en', 'firstname', 'Firstname'),
('', 'en', 'first_name_is_required', 'First name is required'),
('', 'en', 'follow_us_on_facebook', 'Follow us on Facebook'),
('', 'en', 'follow_us_on_google', 'Follow us on Google+'),
('', 'en', 'follow_us_on_twitter', 'Follow us on Twitter'),
('', 'en', 'forget_password', 'Forget Password?'),
('', 'en', 'forget_your_password', 'forget your password'),
('', 'en', 'frequently_asked_questions', 'Frequently Asked Questions'),
('', 'en', 'full_name', 'Full Name'),
('', 'en', 'general_setting', 'General Setting'),
('', 'en', 'google', 'Google+'),
('', 'en', 'google_url', 'Google+ URL'),
('', 'en', 'group', 'Group'),
('', 'en', 'gzip_compress', 'GZIP Compress'),
('', 'en', 'home', 'Home'),
('', 'en', 'howdy', 'Howdy,'),
('', 'en', 'if_you_already_have_an_account', 'If You already have an account'),
('', 'en', 'if_you_dont_have_account', 'If You Dont have account'),
('', 'en', 'in', 'in'),
('', 'en', 'infoposts', 'Posts'),
('', 'en', 'info_add_newphrase', 'To display this text in your template , simple add this where you want to display your text'),
('', 'en', 'info_change_password', 'If you would like to change the password type a new one.<br/>Otherwise leave this blank.'),
('', 'en', 'inf_upload_language', 'Browse Language File ( must be .xml format )'),
('', 'en', 'instagram', 'Instagram'),
('', 'en', 'instagram_url', 'Instagram URL'),
('', 'en', 'isadmin', 'Admin'),
('', 'en', 'items', 'items'),
('', 'en', 'items_per_page', 'Items Per Page'),
('', 'en', 'items_per_popular', 'Items Per Popular'),
('', 'en', 'join_new', 'Join New'),
('', 'en', 'knowledge', 'Knowledge'),
('', 'en', 'knowledge_base', 'Knowledge Base'),
('', 'en', 'lang', 'en'),
('', 'en', 'language', 'Language'),
('', 'en', 'language_code', 'Language Code'),
('', 'en', 'language_name', 'Language Name'),
('', 'en', 'language_regex', 'Language Regex'),
('', 'en', 'language_settings', 'Language Setting'),
('', 'en', 'lastname', 'Lastname'),
('', 'en', 'last_name_is_required', 'Last name is required'),
('', 'en', 'local_time_is', 'Local time is'),
('', 'en', 'location', 'Location'),
('', 'en', 'logged_out', 'logged out'),
('', 'en', 'login', 'Login'),
('', 'en', 'login_admin', 'Login Admin'),
('', 'en', 'login_error', 'Error:Username or password entered were incorrect.'),
('', 'en', 'logout', 'Logout'),
('', 'en', 'make_default', 'Make Default'),
('', 'en', 'make_sure_you_write_your_email_correctly', 'Make sure you write your email correctly.'),
('', 'en', 'member_for', 'Member for'),
('', 'en', 'message', 'Message'),
('', 'en', 'messege_is_required', 'Messege is required.'),
('', 'en', 'mgs_new_password', 'If you would like to change the password type a new one. Otherwise leave this blank.'),
('', 'en', 'modified', 'Modified'),
('', 'en', 'msg_name_must_be_in_english', 'The user name must be in English and does not contain symbols or distance not less than 3 letters and no more than 16 characters. Symbol (_) is permitted.'),
('', 'en', 'name', 'Name'),
('', 'en', 'name_available_registration', 'Username is available for registration.'),
('', 'en', 'name_not_available_registration', 'The name is not available for registration, a user by another user.'),
('', 'en', 'new', 'New'),
('', 'en', 'news', 'News'),
('', 'en', 'news_items', 'news Items'),
('', 'en', 'new_password', 'New Password'),
('', 'en', 'no', 'No'),
('', 'en', 'nof_nopermission', 'Error Permission'),
('', 'en', 'none', 'None'),
('', 'en', 'normal', 'Normal'),
('', 'en', 'not_for_everyone', 'Not for everyone'),
('', 'en', 'not_select_anything', 'Sorry it seems you do not select anything!'),
('', 'en', 'not_valid_format_upload', 'not have a valid format. Upload a png, jpg, gif, jpeg file type'),
('', 'en', 'no_result', 'No Result'),
('', 'en', 'options', 'Options'),
('', 'en', 'order', 'Order'),
('', 'en', 'orders_categorie_successfully', 'Orders Categorie Successfully'),
('', 'en', 'package_name', 'Package Name'),
('', 'en', 'pages', 'Pages'),
('', 'en', 'pages_setting', 'Pages Setting'),
('', 'en', 'page_about', 'Page About'),
('', 'en', 'page_contact', 'Page Contact'),
('', 'en', 'page_privacy', 'Page Privacy'),
('', 'en', 'page_views', 'Page Views'),
('', 'en', 'parent', 'Parent'),
('', 'en', 'password', 'Password'),
('', 'en', 'password_must_be_at_least_6_characters', 'Password must be at least 6 characters.'),
('', 'en', 'phrase', 'Phrase'),
('', 'en', 'phrase_code', 'Phrase Code'),
('', 'en', 'phrase_module', 'Phrase Module'),
('', 'en', 'phrase_text', 'Phrase Text'),
('', 'en', 'pin_post', 'Pin Post'),
('', 'en', 'please_activate_your_account', 'Please activate your account activation message been sent to your registered email'),
('', 'en', 'please_complete_the_fields', 'Please complete the fields'),
('', 'en', 'popular_knowledgebase', 'Popular Knowledgebase'),
('', 'en', 'popular_knowledge_base', 'Popular Knowledge Base'),
('', 'en', 'popular_news', 'Popular News'),
('', 'en', 'posts', 'Posts'),
('', 'en', 'posts_chart', 'Posts Chart'),
('', 'en', 'preview', 'Preview'),
('', 'en', 'privacy', 'privacy'),
('', 'en', 'processing', 'Processing ...'),
('', 'en', 'profile', 'Profile'),
('', 'en', 'public_information', 'Public Information'),
('', 'en', 'publish', 'Publish'),
('', 'en', 'publishnow', 'Publish Now'),
('', 'en', 'register', 'Register'),
('', 'en', 'registration', 'Registration'),
('', 'en', 'registration_activation', 'Registration Activation'),
('', 'en', 'reg_closed', 'Registration is closed at this time!'),
('', 'en', 'reset', 'Reset'),
('', 'en', 'return_to_login', 'Return To Login'),
('', 'en', 're_enter_the_new_email_address', 'Re-enter the new Email address'),
('', 'en', 're_enter_the_new_password', 'Re-enter the new password'),
('', 'en', 'role', 'Role'),
('', 'en', 'save', 'Save'),
('', 'en', 'saved_successfully', 'Saved successfully.'),
('', 'en', 'save_changes', 'Save Changes'),
('', 'en', 'search', 'search'),
('', 'en', 'search_the_knowledge_base', 'search the Knowledge Base ...'),
('', 'en', 'send_message', 'Send Message'),
('', 'en', 'send_your_message_has_been_successfully', 'Send your message has been successfully.'),
('', 'en', 'settings', 'Settings'),
('', 'en', 'show_page_users', 'Show Page Users'),
('', 'en', 'show_profile_users', 'Show Profile Users'),
('', 'en', 'sign_up', 'Sign up'),
('', 'en', 'sign_up_for_your_free', 'sign up for your free'),
('', 'en', 'site_wide_meta_description', 'Site wide Meta Description'),
('', 'en', 'site_wide_meta_keywords', 'Site wide Meta Keywords'),
('', 'en', 'slug', 'Slug'),
('', 'en', 'socials', 'Socials'),
('', 'en', 'socials_setting', 'Socials Setting'),
('', 'en', 'statistics', 'Statistics'),
('', 'en', 'status', 'Status'),
('', 'en', 'subject', 'Subject'),
('', 'en', 'subject_is_required', 'Subject is required.'),
('', 'en', 'tagline', 'Tagline'),
('', 'en', 'template', 'Template'),
('', 'en', 'themes', 'Themes'),
('', 'en', 'themes_setting', 'Themes Setting'),
('', 'en', 'theme_activated_successfully', 'theme activated successfully.'),
('', 'en', 'this_field_is_required', 'This field is required'),
('', 'en', 'timezone', 'Timezone'),
('', 'en', 'time_format', 'Time Format'),
('', 'en', 'title', 'Title'),
('', 'en', 'toggle_navigation', 'Toggle navigation'),
('', 'en', 'twitter', 'Twitter'),
('', 'en', 'twitter_url', 'Twitter URL'),
('', 'en', 'type', 'Type'),
('', 'en', 'unique_visitors', 'Unique Visitors'),
('', 'en', 'up', 'Up'),
('', 'en', 'update', 'Update'),
('', 'en', 'upload', 'Upload'),
('', 'en', 'upload_file', 'Upload file'),
('', 'en', 'used_template', 'used template'),
('', 'en', 'user', 'User'),
('', 'en', 'username', 'Username'),
('', 'en', 'usernames_cannot_be_changed', 'Usernames cannot be changed.'),
('', 'en', 'username_is_required', 'Username is required.'),
('', 'en', 'users', 'Users'),
('', 'en', 'users_chart', 'Users Chart'),
('', 'en', 'users_per_page', 'Users Per Page'),
('', 'en', 'users_setting', 'Users Setting'),
('', 'en', 'user_only', 'User only'),
('', 'en', 'utc_time_is', 'UTC time is'),
('', 'en', 'view', 'View'),
('', 'en', 'views', 'views'),
('', 'en', 'view_my_profile', 'View My Profile'),
('', 'en', 'view_post', 'View Post'),
('', 'en', 'view_profile', 'Views Profile'),
('', 'en', 'visitors_chart', 'Visitors Chart'),
('', 'en', 'visits_the_day', 'Visits The Day'),
('', 'en', 'visits_the_month', 'Visits The Month'),
('', 'en', 'visits_the_year', 'Visits The Year'),
('', 'en', 'visit_site', 'Visit Site'),
('', 'en', 'vote_users_only', 'Vote Users Only'),
('', 'en', 'voting', 'Voting'),
('', 'en', 'voting_chart', 'Voting Chart'),
('', 'en', 'voting_down', 'Voting Down'),
('', 'en', 'voting_up', 'Voting Up'),
('', 'en', 'website', 'Web Site'),
('', 'en', 'website_email', 'Website Email'),
('', 'en', 'website_name', 'Website Name'),
('', 'en', 'website_url', 'Website URL'),
('', 'en', 'welcome', 'Welcome'),
('', 'en', 'well_done', 'Well done!'),
('', 'en', 'yes', 'Yes'),
('', 'en', 'your_current_email_address', 'Your current email address'),
('', 'en', 'youtube', 'Youtube'),
('', 'en', 'youtube_url', 'Youtube URL');